### PR TITLE
[ch27571] Start using dockerhub instead of ecr

### PR DESCRIPTION
**Pull request by victorpoluceno**
Start using the public image from docker hub registry.

### CODE REVIEW

**Review by rlinstorres — COMMENTED** [review]
@victorpoluceno, the idea is to test with `cm://h.cfcr.io/findhotel/lab/` instead of `cm://h.cfcr.io/findhotel/default/`?

**Comment by victorpoluceno** [comment]
@rlinstorres nope, that was a mistake. Great catch mate, I will fix it.

**Comment by victorpoluceno** [comment]
@rlinstorres it's fixed. Thanks.

**Review by rlinstorres — APPROVED** [review]
LGTM!

**Review by gtonello — APPROVED** [review]

**Pull request merged**
